[package]
name = "attack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
array_tool = "1.0.3"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
